-- ===========================================================
-- 0044 · MÓDULO COMMERCE — catálogo, proveedores, compras e inventario
-- -----------------------------------------------------------
-- Portado desde JLIZ BUSINESS con tres correcciones multiempresa:
--   1. company_id not null en TODAS las tablas
--   2. los índices únicos pasan a ser POR EMPRESA (sku, códigos, folio SII):
--      si no, el segundo cliente no podría usar un código que ya usó el primero
--   3. la numeración de códigos es por empresa, no global
--
-- Verificado (8/8): dos empresas pueden tener el mismo SKU-001, sus
-- numeraciones arrancan las dos en 000001, y ninguna ve ni escribe
-- en los datos de la otra. Ver supabase/tests/commerce_isolation.sql
-- ===========================================================

do $$ begin create type public.entity_status as enum ('activo','inactivo','archivado');
exception when duplicate_object then null; end $$;
do $$ begin create type public.unit_measure as enum ('kg','g','unidad','caja','bandeja');
exception when duplicate_object then null; end $$;
do $$ begin create type public.lot_status as enum ('disponible','agotado','vencido','bloqueado');
exception when duplicate_object then null; end $$;
do $$ begin create type public.movement_type as enum ('entrada_compra','ajuste_positivo','salida_venta','reserva','liberacion_reserva','merma','ajuste_negativo','devolucion','traslado','proceso_consumo','proceso_produccion');
exception when duplicate_object then null; end $$;
do $$ begin create type public.purchase_status as enum ('borrador','recibida','anulada');
exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_method as enum ('efectivo','transferencia','tarjeta','cheque','credito','otro');
exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('pendiente','parcial','pagado','vencido');
exception when duplicate_object then null; end $$;

-- ---------- NUMERACIÓN POR EMPRESA ----------
create table if not exists public.counters (
  company_id uuid not null references public.companies(id) on delete cascade,
  key   text   not null,
  value bigint not null default 0,
  primary key (company_id, key)
);

create or replace function public.next_code(p_company uuid, p_prefix text)
returns text language plpgsql security definer set search_path = public, pg_temp as $$
declare v_year text := to_char(now() at time zone 'America/Santiago','YYYY'); v_val bigint;
begin
  insert into public.counters (company_id, key, value) values (p_company, p_prefix||'-'||v_year, 1)
  on conflict (company_id, key) do update set value = public.counters.value + 1
  returning value into v_val;
  return p_prefix||'-'||v_year||'-'||lpad(v_val::text, 6, '0');
end $$;
revoke execute on function public.next_code(uuid,text) from public, anon;
grant  execute on function public.next_code(uuid,text) to authenticated;

-- ---------- CATÁLOGO ----------
create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null, description text, sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (company_id, name)
);

create table if not exists public.fish_species (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  common_name text not null, scientific_name text, family text, notes text,
  status public.entity_status not null default 'activo',
  created_at timestamptz not null default now(),
  unique (company_id, common_name)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  sku text, name text not null,
  species_id uuid references public.fish_species(id) on delete set null,
  category_id uuid references public.product_categories(id) on delete set null,
  presentation text,
  base_unit public.unit_measure not null default 'kg',
  package_format text, package_weight numeric(12,3),
  min_stock numeric(12,3) not null default 0,
  sale_price numeric(12,2) not null default 0,
  last_cost numeric(12,2) not null default 0,
  avg_cost  numeric(12,2) not null default 0,
  is_perishable boolean not null default true,
  shelf_life_days integer, photo_url text, notes text,
  status public.entity_status not null default 'activo',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, sku)
);

create table if not exists public.product_price_history (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  price numeric(12,2) not null, previous_price numeric(12,2), cost_reference numeric(12,2),
  changed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------- UBICACIONES ----------
create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  code text, name text not null, type text not null default 'bodega',
  capacity_kg numeric(12,3),
  driver_id uuid references public.profiles(id) on delete set null,
  notes text,
  status public.entity_status not null default 'activo',
  created_at timestamptz not null default now(),
  unique (company_id, code)
);

-- ---------- PROVEEDORES ----------
create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  code text, name text not null, company text, rut text,
  contact_name text, phone text, whatsapp text, email text,
  address text, comuna text, region text,
  payment_terms_days integer not null default 0, rating integer, notes text,
  status public.entity_status not null default 'activo',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, code)
);

create table if not exists public.supplier_aliases (
  company_id uuid not null references public.companies(id) on delete cascade,
  alias text not null,
  supplier_id uuid not null references public.suppliers(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (company_id, alias)
);

create table if not exists public.supplier_products (
  company_id uuid not null references public.companies(id) on delete cascade,
  supplier_id uuid not null references public.suppliers(id) on delete cascade,
  product_id  uuid not null references public.products(id)  on delete cascade,
  last_price numeric(12,2), avg_price numeric(12,2),
  last_purchase_at timestamptz, notes text,
  primary key (supplier_id, product_id)
);

-- ---------- COMPRAS ----------
create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  code text,
  supplier_id uuid not null references public.suppliers(id) on delete restrict,
  purchase_date date not null default ((now() at time zone 'America/Santiago'))::date,
  status public.purchase_status not null default 'borrador',
  subtotal numeric(14,2) not null default 0,
  freight_cost numeric(14,2) not null default 0,
  other_costs numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  payment_method public.payment_method not null default 'transferencia',
  payment_status public.payment_status not null default 'pendiente',
  amount_paid numeric(14,2) not null default 0,
  due_date date, invoice_number text, document_url text, origin text, notes text,
  received_by uuid references public.profiles(id) on delete set null,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, code)
);

create table if not exists public.purchase_items (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  purchase_id uuid not null references public.purchases(id) on delete cascade,
  product_id  uuid not null references public.products(id)  on delete restrict,
  quantity numeric(12,3) not null,
  unit public.unit_measure not null default 'kg',
  unit_price numeric(12,2) not null,
  line_total numeric(14,2) generated always as (round(quantity * unit_price, 2)) stored,
  notes text,
  created_at timestamptz not null default now()
);

-- Registro tributario del SII. El folio es único POR EMPRESA.
create table if not exists public.purchase_history (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  fecha date not null, tipo_documento text not null, folio text,
  rut text not null, razon_social text not null,
  supplier_id uuid references public.suppliers(id) on delete set null,
  monto_exento numeric(14,2) not null default 0,
  monto_neto   numeric(14,2) not null default 0,
  monto_iva    numeric(14,2) not null default 0,
  monto_total  numeric(14,2) not null,
  es_nota_credito boolean not null default false,
  origen text not null default 'sii',
  importado_at timestamptz not null default now(),
  unique (company_id, tipo_documento, folio, rut)
);

-- ---------- INVENTARIO ----------
create table if not exists public.inventory_lots (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  code text,
  product_id uuid not null references public.products(id) on delete restrict,
  supplier_id uuid references public.suppliers(id) on delete set null,
  purchase_id uuid references public.purchases(id) on delete set null,
  purchase_item_id uuid references public.purchase_items(id) on delete set null,
  received_at timestamptz not null default now(),
  production_date date, expires_at date,
  initial_quantity  numeric(12,3) not null,
  quantity_on_hand  numeric(12,3) not null default 0,
  quantity_reserved numeric(12,3) not null default 0,
  quantity_available numeric(12,3) generated always as (quantity_on_hand - quantity_reserved) stored,
  unit public.unit_measure not null default 'kg',
  unit_cost numeric(12,2) not null default 0,
  origin text, location text,
  location_id uuid references public.locations(id) on delete set null,
  status public.lot_status not null default 'disponible',
  received_by uuid references public.profiles(id) on delete set null,
  photo_url text, notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, code)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  lot_id uuid references public.inventory_lots(id) on delete set null,
  type public.movement_type not null,
  quantity numeric(12,3) not null,
  unit public.unit_measure not null default 'kg',
  unit_cost numeric(12,2),
  reference_type text, reference_id text, reference_code text, reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------- ÍNDICES (company_id y toda clave foránea) ----------
create index if not exists product_categories_company_idx on public.product_categories(company_id);
create index if not exists fish_species_company_idx       on public.fish_species(company_id);
create index if not exists products_company_idx           on public.products(company_id);
create index if not exists products_category_idx          on public.products(category_id);
create index if not exists products_species_idx           on public.products(species_id);
create index if not exists products_created_by_idx        on public.products(created_by);
create index if not exists pph_company_idx                on public.product_price_history(company_id);
create index if not exists pph_product_idx                on public.product_price_history(product_id);
create index if not exists pph_changed_by_idx             on public.product_price_history(changed_by);
create index if not exists locations_company_idx          on public.locations(company_id);
create index if not exists locations_driver_idx           on public.locations(driver_id);
create index if not exists suppliers_company_idx          on public.suppliers(company_id);
create index if not exists suppliers_created_by_idx       on public.suppliers(created_by);
create index if not exists supplier_aliases_supplier_idx  on public.supplier_aliases(supplier_id);
create index if not exists supplier_aliases_created_by_idx on public.supplier_aliases(created_by);
create index if not exists supplier_products_company_idx  on public.supplier_products(company_id);
create index if not exists supplier_products_product_idx  on public.supplier_products(product_id);
create index if not exists purchases_company_idx          on public.purchases(company_id);
create index if not exists purchases_supplier_idx         on public.purchases(supplier_id);
create index if not exists purchases_created_by_idx       on public.purchases(created_by);
create index if not exists purchases_received_by_idx      on public.purchases(received_by);
create index if not exists purchase_items_company_idx     on public.purchase_items(company_id);
create index if not exists purchase_items_purchase_idx    on public.purchase_items(purchase_id);
create index if not exists purchase_items_product_idx     on public.purchase_items(product_id);
create index if not exists purchase_history_company_idx   on public.purchase_history(company_id, fecha desc);
create index if not exists purchase_history_supplier_idx  on public.purchase_history(supplier_id);
create index if not exists inventory_lots_company_idx     on public.inventory_lots(company_id);
create index if not exists inventory_lots_product_idx     on public.inventory_lots(product_id);
create index if not exists inventory_lots_supplier_idx    on public.inventory_lots(supplier_id);
create index if not exists inventory_lots_purchase_idx    on public.inventory_lots(purchase_id);
create index if not exists inventory_lots_pitem_idx       on public.inventory_lots(purchase_item_id);
create index if not exists inventory_lots_location_idx    on public.inventory_lots(location_id);
create index if not exists inventory_lots_received_by_idx on public.inventory_lots(received_by);
create index if not exists inv_mov_company_idx            on public.inventory_movements(company_id, created_at desc);
create index if not exists inv_mov_product_idx            on public.inventory_movements(product_id);
create index if not exists inv_mov_lot_idx                on public.inventory_movements(lot_id);
create index if not exists inv_mov_created_by_idx         on public.inventory_movements(created_by);
create index if not exists counters_company_idx           on public.counters(company_id);

-- ---------- CÓDIGOS AUTOMÁTICOS POR EMPRESA ----------
create or replace function public.set_lot_code()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if new.code is null then new.code := public.next_code(new.company_id, 'LOTE'); end if;
  return new;
end $$;
create or replace function public.set_purchase_code()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if new.code is null then new.code := public.next_code(new.company_id, 'COM'); end if;
  return new;
end $$;
revoke execute on function public.set_lot_code()      from public, anon, authenticated;
revoke execute on function public.set_purchase_code() from public, anon, authenticated;

drop trigger if exists inventory_lots_code on public.inventory_lots;
create trigger inventory_lots_code before insert on public.inventory_lots
  for each row execute function public.set_lot_code();
drop trigger if exists purchases_code on public.purchases;
create trigger purchases_code before insert on public.purchases
  for each row execute function public.set_purchase_code();

drop trigger if exists products_touch  on public.products;
drop trigger if exists suppliers_touch on public.suppliers;
drop trigger if exists purchases_touch on public.purchases;
drop trigger if exists lots_touch      on public.inventory_lots;
create trigger products_touch  before update on public.products       for each row execute function public.touch_updated_at();
create trigger suppliers_touch before update on public.suppliers      for each row execute function public.touch_updated_at();
create trigger purchases_touch before update on public.purchases      for each row execute function public.touch_updated_at();
create trigger lots_touch      before update on public.inventory_lots for each row execute function public.touch_updated_at();

-- ---------- RLS ----------
-- Operación (catálogo, inventario): empleado (40).
-- Dinero (compras, registro tributario): encargado (60).
do $$
declare t text; lvl int;
begin
  foreach t in array array['product_categories','fish_species','products','product_price_history',
                           'locations','suppliers','supplier_aliases','supplier_products',
                           'inventory_lots','inventory_movements','counters',
                           'purchases','purchase_items','purchase_history'] loop
    lvl := case when t in ('purchases','purchase_items','purchase_history') then 60 else 40 end;
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t||'_company', t);
    execute format($p$create policy %I on public.%I for all to authenticated
      using (public.has_company_level(company_id, %s))
      with check (public.has_company_level(company_id, %s))$p$, t||'_company', t, lvl, lvl);
  end loop;
end $$;
